# Generated by Django 4.2.6 on 2023-10-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
