# Generated by Django 4.2.6 on 2023-10-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_conta_transferencias_realizadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='transferencias_realizadas',
        ),
    ]
