# Generated by Django 4.2.6 on 2023-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_conta_transferencias_realizadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='transferencias_realizadas',
            field=models.ManyToManyField(to='core.transferencia'),
        ),
    ]
