# Generated by Django 4.2.6 on 2023-10-12 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_conta_transferencias_realizadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='transferencias_realizadas',
        ),
        migrations.AddField(
            model_name='conta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
