# Generated by Django 4.2.6 on 2023-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_status_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='data_exp',
            field=models.DateField(null=True),
        ),
    ]
