# Generated by Django 4.2.6 on 2023-11-21 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_locked_at_user_login_attempts_user_unlocked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorRequisitado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('qtd_parcelas', models.IntegerField()),
                ('status', models.CharField(default='Em Análise', max_length=20)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos', to='core.conta')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorParcela', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorPago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numParcela', models.IntegerField()),
                ('dataVencimento', models.DateField()),
                ('dataPaga', models.DateField(null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimos_parcelas', to='core.emprestimo')),
            ],
        ),
    ]
