# Generated by Django 4.2.6 on 2023-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cartao_limite_alter_conta_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='Em Análise', max_length=255),
        ),
    ]
